# Generated by Django 3.1.4 on 2020-12-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0002_auto_20201214_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
