# Generated by Django 3.1.4 on 2020-12-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0003_auto_20201215_1558'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
