# Generated by Django 3.1.4 on 2020-12-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_api', '0004_auto_20201215_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
